name: cisco_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.6+2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/