// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmoux2-AOhmQKwwuXJB89gm0n7sRg9Y1o',
    appId: '1:1017629534962:web:45f6f64b328d9302707e6b',
    messagingSenderId: '1017629534962',
    projectId: 'cisco-map-417104',
    authDomain: 'cisco-map-417104.firebaseapp.com',
    databaseURL: 'https://cisco-map-417104-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cisco-map-417104.appspot.com',
    measurementId: 'G-8W1LLPBW1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXWK29KLEKjrTOaXoikIvCjJRXrZC0w7U',
    appId: '1:1017629534962:android:533a2779e6211269707e6b',
    messagingSenderId: '1017629534962',
    projectId: 'cisco-map-417104',
    databaseURL: 'https://cisco-map-417104-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cisco-map-417104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzpm2z9OjVmkErGfRWIOycCrT7ysTe0v4',
    appId: '1:1017629534962:ios:e1b38c3132d29f71707e6b',
    messagingSenderId: '1017629534962',
    projectId: 'cisco-map-417104',
    databaseURL: 'https://cisco-map-417104-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cisco-map-417104.appspot.com',
    iosBundleId: 'com.example.ciscoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzpm2z9OjVmkErGfRWIOycCrT7ysTe0v4',
    appId: '1:1017629534962:ios:8b38e031e641a478707e6b',
    messagingSenderId: '1017629534962',
    projectId: 'cisco-map-417104',
    databaseURL: 'https://cisco-map-417104-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cisco-map-417104.appspot.com',
    iosBundleId: 'com.example.ciscoApp.RunnerTests',
  );
}
